server:
  port: 8000
  read_timeout_seconds: 5
  write_timeout_seconds: 10

cookie_domain: "localhost"

endpoints:
  backend_base_url: "http://localhost:8000"
  frontend_base_url: "http://localhost:5173"
